version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    container_name: fastapi_app

  ngrok:
    image: wernight/ngrok
    depends_on:
      - fastapi
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
      - NGROK_REGION=us
    command: http fastapi:8000
